name: Angular CI/CD

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch

jobs:
  buildIt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Specify your Node.js version

      - name: Install dependencies
        run: npm ci
        #run: npm install

      # - name: Run unit tests
        # run: npm test -- --no-watch --browsers=ChromeHeadless # Run tests in a headless browser

      - name: Build Angular application
        run: npm run build -- --configuration=production

      - name: List dist directory contents 1
        run: ls -R /home/runner/work/PgmrCalc/PgmrCalc/export/

  deployIt:
    needs: buildIt
    runs-on: ubuntu-latest
    
    steps:
      # - name: Checkout content
      #   uses: actions/checkout@v4

      # - name: List directory contents
      #   run: ls -R /home/runner/work/PgmrCalc/PgmrCalc/

      - name: setup directory
        run: mkdir -p /home/runner/work/PgmrCalc/PgmrCalc/export

      - name: List dist directory contents
        run: ls -R /home/runner/work/PgmrCalc/PgmrCalc/export/

      - name: FTP Deploy
        uses: SamKirkland/Ftp-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}         # Your FTP server address
          username: ${{ secrets.FTP_USERNAME }}     # Your FTP username
          password: ${{ secrets.FTP_PASSWORD }}     # Your FTP password
          port: 21

          # Output Location: /home/runner/work/PgmrCalc/PgmrCalc/dist/pgmr-calc ?!
          
          # local-dir: ./dist/pgmr-calc/     # Path to your local build directory FAILED
          # local-dir: /pgmr-calc/         # Path to your local build directory FAILED
          # local-dir: /dist/pgmr-calc/         # Path to your local build directory FAILED
          # local-dir: ./dist/               # Path to your local build directory 
          # local-dir: PgmrCalc/dist/pgmr-calc/         # Path to your local build directory 
          local-dir: /home/runner/work/PgmrCalc/PgmrCalc/export/ # this deploys but does not work

          server-dir: /public_html/PgmrCalc/         # Path on FTP server to deploy 