name: Angular CI/CD

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch

jobs:
  buildIt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Specify your Node.js version

      - name: Install dependencies
        run: npm ci
        #run: npm install

      - name: Build Angular application
        run: npm run build -- --configuration=production --base-href=/PgmrCalc/browser/
      - name: List dist directory contents 
        run: ls -R /home/runner/work/PgmrCalc/PgmrCalc/dist/PgmrCalc

      - name: FTP Deploy
        uses: SamKirkland/Ftp-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}         # Your FTP server address
          username: ${{ secrets.FTP_USERNAME }}     # Your FTP username
          password: ${{ secrets.FTP_PASSWORD }}     # Your FTP password
          port: 21
          local-dir: ./dist/PgmrCalc/ # this deploys but does not work
          server-dir: /public_html/PgmrCalc/         # Path on FTP server to deploy 